# Decide on language to use here,
 language: python

 python:
  - "3.6"
#
# Use services as such,
#
# services:
#   - docker
#
# before_install:
#
 script:
# - docker ps -a
  - python unit_test.py

# after_success:

