version: '3'
services:
  ### SERVER ###
  server:
    build: ./server
    expose:
      - ${API_SERVER_PORT}
    environment:
      API_HOST: ${API_HOST}
      API_SERVER_PORT: ${API_SERVER_PORT}
    volumes:
      - ./server:/src/app/internado-server/server
      - /app/node_modules
    ports: #HOST:CONTAINER
      - ${API_SERVER_PORT}:${API_SERVER_PORT}
    environment:
      WAIT_SLEEP_INTERVAL: 60 
      WAIT_HOSTS_TIMEOUT: 600
      WAIT_HOSTS: postgres:5432
    depends_on:
      - "postgres"

  #### DATABASE ###
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: internado
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - database_data:/var/lib/postgresql/data
      - ./database_config/init.sql:/docker-entrypoint-initdb.d/init.sql
      
  adminer:
    image: adminer
    restart: always
    depends_on:
      - "postgres"
    ports:
      - 8080:8080

  ### CLIENT ###
  client:
    build: ./client
    environment:
      CLIENT_PORT: ${CLIENT_PORT}
    expose:
      - ${CLIENT_PORT}
    volumes:
      - ./client/src:/src/app/internado-client/client/src
      - /app/node_modules
    ports: #HOST:CONTAINER
      - ${CLIENT_PORT}:${CLIENT_PORT}
    links:
      - server
    command: npm start

volumes:
  database_data:
    driver: local