version: '3'
services:
  ### SERVER ###
  server:
    build: ./server
    expose:
      - ${API_SERVER_PORT}
    environment:
      API_HOST: ${API_HOST}
      API_SERVER_PORT: ${API_SERVER_PORT}
    command: npm start
    volumes:
      - ./server:/src/app/internado-server/server
      - /app/node_modules
    ports: #HOST:CONTAINER
      - ${API_SERVER_PORT}:${API_SERVER_PORT}
  ### CLIENT ###
  client:
    build: ./client
    environment:
      CLIENT_PORT: ${CLIENT_PORT}
    expose:
      - ${CLIENT_PORT}
    volumes:
      - ./client/src:/src/app/internado-client/client/src
      - /app/node_modules
    ports: #HOST:CONTAINER
      - ${CLIENT_PORT}:${CLIENT_PORT}
    links:
      - server
    command: npm start

